### ISSUE TITLE
Release v0.2.0-alpha

### ISSUE THREAD

**Issue by RossComputerGuy** [ExpidusOS-archive/sdk#10]
This is the first in many issues which is a set of proposals and features which are planned for specific versions of ExpidusOS.

# RFC's

1. Add SELinux policies to further limit Mainline and Tinker variants

# Tasks

## `pkgs`

- [ ] Add [`libtokyo`](https://github.com/ExpidusOS/libtokyo) refactored for Neutron
- [ ] Add [Genesis Shell](https://github.com/ExpidusOS/genesis)
- [ ] Add [Gokai](https://github.com/ExpidusOS/gokai) Framework
- [ ] Add utility to SDK which creates aliases similar to phases in Nixpkgs for dev shell

### DevKit

*TODO*: Will be added once we further understand the scope of this.

### Droid

*NOTE*: Will be updated more once we further understand the scope of this.

- [ ] Begin work with Nix modules and use AOSP as base
- [ ] Add [Genesis Shell](https://github.com/ExpidusOS/genesis)
- [ ] [Launcher](https://github.com/ExpidusOS/launcher) add as a module

### Mainline

*NOTE*: Will be updated more once we further understand the scope of this.

- [ ] [Launcher](https://github.com/ExpidusOS/launcher) add as a module
- [ ] Add VM module for easy testing
- [ ] Add AppArmor profiles
- [ ] Add EPK module for adding to both datafs and rootfs

### Tinker

*TODO*: Will be added once we further understand the scope of this.

# Nixpkgs

## PR's

- [x] https://github.com/NixOS/nixpkgs/pull/206655
- [ ] https://github.com/NixOS/nixpkgs/pull/212328
- [x] https://github.com/NixOS/nixpkgs/pull/157056
